name: token_storage
description: Token storage for the authentication client.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.2
  test: ^1.25.1
  very_good_analysis: ^6.0.0
