name: powersync_repository
description: A package that manages connection to the Powersync cloud service and database.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  env:
    path: ../env
  
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.1
  powersync: ^0.4.1
  shared:
    path: ../shared
  supabase_flutter: ^1.10.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
