name: notifications_client

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/notifications_client/notifications_client/**"
      - ".github/workflows/notifications_client.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: 3.3.4
      working_directory: packages/notifications_client/notifications_client
